media: images
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [ title, date ]
    fields:
      - name: layout
        label: Layout
        type: string
        default: post
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: rich-text
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: image
      - name: tags
        label: Tags
        type: string